name: Test Link CLion EAP

on:
  schedule:
    - cron: "0 12 * * *"

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install links package
        run: sudo apt install links

      - name: Test downloads link for clion aur
        run: wget --server-response --spider --quiet "https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=clion-eap"

      - name: Search version for CLion EAP
        run: |
          link="https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=clion-eap"
          version=( $(grep -Eo "([0-9]+[.])+[0-9]+" <(links -dump $link)) )
          printf "latest version: ${version[0]} ${version[1]} \n" >> $GITHUB_STEP_SUMMARY

      - name: Test download link for CLion EAP
        run: |
          link="https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=clion-eap"
          version=( $(grep -Eo "([0-9]+[.])+[0-9]+" <(links -dump $link)) )
          link_prg1="https://download.jetbrains.com/cpp/CLion-${version[0]}.tar.gz"
          link_prg2="https://download.jetbrains.com/cpp/CLion-${version[1]}.tar.gz"
          wget --server-response --spider --quiet "$link_prg1" || wget --server-response --spider --quiet "$link_prg2"

      - name: Check appimagetool link
        run: wget --server-response --spider --quiet "https://github.com/AppImage/AppImageKit/releases/download/13/appimagetool-x86_64.AppImage"
